/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4eec413522256b0956ffb5d0024a81b8)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	KAD_PRODUCTS_ENVIRONMENT: "integration" | "staging" | "production" | "development";
	LOG_LEVEL: "debug";
	LOG_LEVEL_TASK_OVERRIDE: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface IntegrationEnv {
		ASSETS: Fetcher;
		KAD_PRODUCTS_ENVIRONMENT: "integration";
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		KAD_PRODUCTS_ENVIRONMENT: "staging";
	}
	interface ProductionEnv {
		ASSETS: Fetcher;
		KAD_PRODUCTS_ENVIRONMENT: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KAD_PRODUCTS_ENVIRONMENT" | "LOG_LEVEL" | "LOG_LEVEL_TASK_OVERRIDE">> {}
}
