name: Verify Changes

on:
  pull_request:
    branches: [main]

jobs:
  lint-code:
    uses: kad-products/platform/.github/workflows/lint-code.yaml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit

  run-tests:
    uses: kad-products/platform/.github/workflows/run-tests.yaml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit