name: Verify Changes

on:
  pull_request:
    branches: [main]

jobs:
  lint-code:
    uses: kad-products/platform/.github/workflows/lint-code.yaml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit

  run-tests:
    uses: kad-products/platform/.github/workflows/run-tests.yaml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit

  plan-github-setup:
    uses: kad-products/platform/.github/workflows/plan-open-tofu.yaml@main
    with:
      app-name: ${{github.event.repository.name}}
      state-type: github
      state-name: setup
      working-directory: infra/github
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit    